set(_CATKIN_CURRENT_PACKAGE "capra_camera")
set(capra_camera_MAINTAINER "capra <capra@todo.todo>")
set(capra_camera_DEPRECATED "")
set(capra_camera_VERSION "0.0.0")
set(capra_camera_BUILD_DEPENDS "rospy" "sensor_msgs")
set(capra_camera_RUN_DEPENDS "rospy" "sensor_msgs" "cv_bridge")
set(capra_camera_BUILDTOOL_DEPENDS "catkin")