// Generated by gencpp from file microstrain_3dmgx1_imu/CalibrateRequest.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_3DMGX1_IMU_MESSAGE_CALIBRATEREQUEST_H
#define MICROSTRAIN_3DMGX1_IMU_MESSAGE_CALIBRATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace microstrain_3dmgx1_imu
{
template <class ContainerAllocator>
struct CalibrateRequest_
{
  typedef CalibrateRequest_<ContainerAllocator> Type;

  CalibrateRequest_()
    : is_2d(false)
    , magnitude_z(0)
    , calibration_time(0)  {
    }
  CalibrateRequest_(const ContainerAllocator& _alloc)
    : is_2d(false)
    , magnitude_z(0)
    , calibration_time(0)  {
    }



   typedef uint8_t _is_2d_type;
  _is_2d_type is_2d;

   typedef int16_t _magnitude_z_type;
  _magnitude_z_type magnitude_z;

   typedef int8_t _calibration_time_type;
  _calibration_time_type calibration_time;




  typedef boost::shared_ptr< ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CalibrateRequest_

typedef ::microstrain_3dmgx1_imu::CalibrateRequest_<std::allocator<void> > CalibrateRequest;

typedef boost::shared_ptr< ::microstrain_3dmgx1_imu::CalibrateRequest > CalibrateRequestPtr;
typedef boost::shared_ptr< ::microstrain_3dmgx1_imu::CalibrateRequest const> CalibrateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace microstrain_3dmgx1_imu

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c715151b405532ed910c498c3183c86";
  }

  static const char* value(const ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c715151b405532eULL;
  static const uint64_t static_value2 = 0xd910c498c3183c86ULL;
};

template<class ContainerAllocator>
struct DataType< ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "microstrain_3dmgx1_imu/CalibrateRequest";
  }

  static const char* value(const ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_2d\n\
int16 magnitude_z\n\
int8 calibration_time\n\
";
  }

  static const char* value(const ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_2d);
      stream.next(m.magnitude_z);
      stream.next(m.calibration_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CalibrateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::microstrain_3dmgx1_imu::CalibrateRequest_<ContainerAllocator>& v)
  {
    s << indent << "is_2d: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_2d);
    s << indent << "magnitude_z: ";
    Printer<int16_t>::stream(s, indent + "  ", v.magnitude_z);
    s << indent << "calibration_time: ";
    Printer<int8_t>::stream(s, indent + "  ", v.calibration_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROSTRAIN_3DMGX1_IMU_MESSAGE_CALIBRATEREQUEST_H
