// Generated by gencpp from file microstrain_3dmgx1_imu/CalibrateResponse.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_3DMGX1_IMU_MESSAGE_CALIBRATERESPONSE_H
#define MICROSTRAIN_3DMGX1_IMU_MESSAGE_CALIBRATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace microstrain_3dmgx1_imu
{
template <class ContainerAllocator>
struct CalibrateResponse_
{
  typedef CalibrateResponse_<ContainerAllocator> Type;

  CalibrateResponse_()
    {
    }
  CalibrateResponse_(const ContainerAllocator& _alloc)
    {
    }






  typedef boost::shared_ptr< ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CalibrateResponse_

typedef ::microstrain_3dmgx1_imu::CalibrateResponse_<std::allocator<void> > CalibrateResponse;

typedef boost::shared_ptr< ::microstrain_3dmgx1_imu::CalibrateResponse > CalibrateResponsePtr;
typedef boost::shared_ptr< ::microstrain_3dmgx1_imu::CalibrateResponse const> CalibrateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace microstrain_3dmgx1_imu

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "microstrain_3dmgx1_imu/CalibrateResponse";
  }

  static const char* value(const ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CalibrateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::microstrain_3dmgx1_imu::CalibrateResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MICROSTRAIN_3DMGX1_IMU_MESSAGE_CALIBRATERESPONSE_H
