// Generated by gencpp from file ros_vision/AddInput.msg
// DO NOT EDIT!


#ifndef ROS_VISION_MESSAGE_ADDINPUT_H
#define ROS_VISION_MESSAGE_ADDINPUT_H

#include <ros/service_traits.h>


#include <ros_vision/AddInputRequest.h>
#include <ros_vision/AddInputResponse.h>


namespace ros_vision
{

struct AddInput
{

typedef AddInputRequest Request;
typedef AddInputResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddInput
} // namespace ros_vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vision::AddInput > {
  static const char* value()
  {
    return "8f11915b22b276d2fb5587b35400289d";
  }

  static const char* value(const ::ros_vision::AddInput&) { return value(); }
};

template<>
struct DataType< ::ros_vision::AddInput > {
  static const char* value()
  {
    return "ros_vision/AddInput";
  }

  static const char* value(const ::ros_vision::AddInput&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vision::AddInputRequest> should match 
// service_traits::MD5Sum< ::ros_vision::AddInput > 
template<>
struct MD5Sum< ::ros_vision::AddInputRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::AddInput >::value();
  }
  static const char* value(const ::ros_vision::AddInputRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::AddInputRequest> should match 
// service_traits::DataType< ::ros_vision::AddInput > 
template<>
struct DataType< ::ros_vision::AddInputRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vision::AddInput >::value();
  }
  static const char* value(const ::ros_vision::AddInputRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vision::AddInputResponse> should match 
// service_traits::MD5Sum< ::ros_vision::AddInput > 
template<>
struct MD5Sum< ::ros_vision::AddInputResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::AddInput >::value();
  }
  static const char* value(const ::ros_vision::AddInputResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::AddInputResponse> should match 
// service_traits::DataType< ::ros_vision::AddInput > 
template<>
struct DataType< ::ros_vision::AddInputResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vision::AddInput >::value();
  }
  static const char* value(const ::ros_vision::AddInputResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VISION_MESSAGE_ADDINPUT_H
