// Generated by gencpp from file ros_vision/AddInputRequest.msg
// DO NOT EDIT!


#ifndef ROS_VISION_MESSAGE_ADDINPUTREQUEST_H
#define ROS_VISION_MESSAGE_ADDINPUTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_vision
{
template <class ContainerAllocator>
struct AddInputRequest_
{
  typedef AddInputRequest_<ContainerAllocator> Type;

  AddInputRequest_()
    : name()
    , type()  {
    }
  AddInputRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , type(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;




  typedef boost::shared_ptr< ::ros_vision::AddInputRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_vision::AddInputRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddInputRequest_

typedef ::ros_vision::AddInputRequest_<std::allocator<void> > AddInputRequest;

typedef boost::shared_ptr< ::ros_vision::AddInputRequest > AddInputRequestPtr;
typedef boost::shared_ptr< ::ros_vision::AddInputRequest const> AddInputRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_vision::AddInputRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_vision::AddInputRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'ros_vision': ['/home/capra/Ibex/src/ros_vision/msg', '/home/capra/Ibex/src/ros_vision/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_vision::AddInputRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_vision::AddInputRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vision::AddInputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vision::AddInputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vision::AddInputRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vision::AddInputRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_vision::AddInputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f11915b22b276d2fb5587b35400289d";
  }

  static const char* value(const ::ros_vision::AddInputRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f11915b22b276d2ULL;
  static const uint64_t static_value2 = 0xfb5587b35400289dULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_vision::AddInputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_vision/AddInputRequest";
  }

  static const char* value(const ::ros_vision::AddInputRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_vision::AddInputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
string type\n\
";
  }

  static const char* value(const ::ros_vision::AddInputRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_vision::AddInputRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AddInputRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_vision::AddInputRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_vision::AddInputRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_VISION_MESSAGE_ADDINPUTREQUEST_H
