// Generated by gencpp from file ros_vision/CreateFilter.msg
// DO NOT EDIT!


#ifndef ROS_VISION_MESSAGE_CREATEFILTER_H
#define ROS_VISION_MESSAGE_CREATEFILTER_H

#include <ros/service_traits.h>


#include <ros_vision/CreateFilterRequest.h>
#include <ros_vision/CreateFilterResponse.h>


namespace ros_vision
{

struct CreateFilter
{

typedef CreateFilterRequest Request;
typedef CreateFilterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CreateFilter
} // namespace ros_vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vision::CreateFilter > {
  static const char* value()
  {
    return "16b9d386bb76c23d41cb22903acca9fc";
  }

  static const char* value(const ::ros_vision::CreateFilter&) { return value(); }
};

template<>
struct DataType< ::ros_vision::CreateFilter > {
  static const char* value()
  {
    return "ros_vision/CreateFilter";
  }

  static const char* value(const ::ros_vision::CreateFilter&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vision::CreateFilterRequest> should match 
// service_traits::MD5Sum< ::ros_vision::CreateFilter > 
template<>
struct MD5Sum< ::ros_vision::CreateFilterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::CreateFilter >::value();
  }
  static const char* value(const ::ros_vision::CreateFilterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::CreateFilterRequest> should match 
// service_traits::DataType< ::ros_vision::CreateFilter > 
template<>
struct DataType< ::ros_vision::CreateFilterRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vision::CreateFilter >::value();
  }
  static const char* value(const ::ros_vision::CreateFilterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vision::CreateFilterResponse> should match 
// service_traits::MD5Sum< ::ros_vision::CreateFilter > 
template<>
struct MD5Sum< ::ros_vision::CreateFilterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::CreateFilter >::value();
  }
  static const char* value(const ::ros_vision::CreateFilterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::CreateFilterResponse> should match 
// service_traits::DataType< ::ros_vision::CreateFilter > 
template<>
struct DataType< ::ros_vision::CreateFilterResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vision::CreateFilter >::value();
  }
  static const char* value(const ::ros_vision::CreateFilterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VISION_MESSAGE_CREATEFILTER_H
