// Generated by gencpp from file ros_vision/DeleteFilterGroup.msg
// DO NOT EDIT!


#ifndef ROS_VISION_MESSAGE_DELETEFILTERGROUP_H
#define ROS_VISION_MESSAGE_DELETEFILTERGROUP_H

#include <ros/service_traits.h>


#include <ros_vision/DeleteFilterGroupRequest.h>
#include <ros_vision/DeleteFilterGroupResponse.h>


namespace ros_vision
{

struct DeleteFilterGroup
{

typedef DeleteFilterGroupRequest Request;
typedef DeleteFilterGroupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeleteFilterGroup
} // namespace ros_vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vision::DeleteFilterGroup > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::ros_vision::DeleteFilterGroup&) { return value(); }
};

template<>
struct DataType< ::ros_vision::DeleteFilterGroup > {
  static const char* value()
  {
    return "ros_vision/DeleteFilterGroup";
  }

  static const char* value(const ::ros_vision::DeleteFilterGroup&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vision::DeleteFilterGroupRequest> should match 
// service_traits::MD5Sum< ::ros_vision::DeleteFilterGroup > 
template<>
struct MD5Sum< ::ros_vision::DeleteFilterGroupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::DeleteFilterGroup >::value();
  }
  static const char* value(const ::ros_vision::DeleteFilterGroupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::DeleteFilterGroupRequest> should match 
// service_traits::DataType< ::ros_vision::DeleteFilterGroup > 
template<>
struct DataType< ::ros_vision::DeleteFilterGroupRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vision::DeleteFilterGroup >::value();
  }
  static const char* value(const ::ros_vision::DeleteFilterGroupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vision::DeleteFilterGroupResponse> should match 
// service_traits::MD5Sum< ::ros_vision::DeleteFilterGroup > 
template<>
struct MD5Sum< ::ros_vision::DeleteFilterGroupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::DeleteFilterGroup >::value();
  }
  static const char* value(const ::ros_vision::DeleteFilterGroupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::DeleteFilterGroupResponse> should match 
// service_traits::DataType< ::ros_vision::DeleteFilterGroup > 
template<>
struct DataType< ::ros_vision::DeleteFilterGroupResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vision::DeleteFilterGroup >::value();
  }
  static const char* value(const ::ros_vision::DeleteFilterGroupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VISION_MESSAGE_DELETEFILTERGROUP_H
