// Generated by gencpp from file ros_vision/DeleteFilter.msg
// DO NOT EDIT!


#ifndef ROS_VISION_MESSAGE_DELETEFILTER_H
#define ROS_VISION_MESSAGE_DELETEFILTER_H

#include <ros/service_traits.h>


#include <ros_vision/DeleteFilterRequest.h>
#include <ros_vision/DeleteFilterResponse.h>


namespace ros_vision
{

struct DeleteFilter
{

typedef DeleteFilterRequest Request;
typedef DeleteFilterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeleteFilter
} // namespace ros_vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vision::DeleteFilter > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::ros_vision::DeleteFilter&) { return value(); }
};

template<>
struct DataType< ::ros_vision::DeleteFilter > {
  static const char* value()
  {
    return "ros_vision/DeleteFilter";
  }

  static const char* value(const ::ros_vision::DeleteFilter&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vision::DeleteFilterRequest> should match 
// service_traits::MD5Sum< ::ros_vision::DeleteFilter > 
template<>
struct MD5Sum< ::ros_vision::DeleteFilterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::DeleteFilter >::value();
  }
  static const char* value(const ::ros_vision::DeleteFilterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::DeleteFilterRequest> should match 
// service_traits::DataType< ::ros_vision::DeleteFilter > 
template<>
struct DataType< ::ros_vision::DeleteFilterRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vision::DeleteFilter >::value();
  }
  static const char* value(const ::ros_vision::DeleteFilterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vision::DeleteFilterResponse> should match 
// service_traits::MD5Sum< ::ros_vision::DeleteFilter > 
template<>
struct MD5Sum< ::ros_vision::DeleteFilterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::DeleteFilter >::value();
  }
  static const char* value(const ::ros_vision::DeleteFilterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::DeleteFilterResponse> should match 
// service_traits::DataType< ::ros_vision::DeleteFilter > 
template<>
struct DataType< ::ros_vision::DeleteFilterResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vision::DeleteFilter >::value();
  }
  static const char* value(const ::ros_vision::DeleteFilterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VISION_MESSAGE_DELETEFILTER_H
