// Generated by gencpp from file ros_vision/Filter.msg
// DO NOT EDIT!


#ifndef ROS_VISION_MESSAGE_FILTER_H
#define ROS_VISION_MESSAGE_FILTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ros_vision/IODescriptor.h>
#include <ros_vision/IODescriptor.h>
#include <ros_vision/Parameter.h>

namespace ros_vision
{
template <class ContainerAllocator>
struct Filter_
{
  typedef Filter_<ContainerAllocator> Type;

  Filter_()
    : name()
    , type()
    , description()
    , inputs()
    , outputs()
    , parameters()  {
    }
  Filter_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , type(_alloc)
    , description(_alloc)
    , inputs(_alloc)
    , outputs(_alloc)
    , parameters(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_type;
  _description_type description;

   typedef std::vector< ::ros_vision::IODescriptor_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ros_vision::IODescriptor_<ContainerAllocator> >::other >  _inputs_type;
  _inputs_type inputs;

   typedef std::vector< ::ros_vision::IODescriptor_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ros_vision::IODescriptor_<ContainerAllocator> >::other >  _outputs_type;
  _outputs_type outputs;

   typedef std::vector< ::ros_vision::Parameter_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ros_vision::Parameter_<ContainerAllocator> >::other >  _parameters_type;
  _parameters_type parameters;




  typedef boost::shared_ptr< ::ros_vision::Filter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_vision::Filter_<ContainerAllocator> const> ConstPtr;

}; // struct Filter_

typedef ::ros_vision::Filter_<std::allocator<void> > Filter;

typedef boost::shared_ptr< ::ros_vision::Filter > FilterPtr;
typedef boost::shared_ptr< ::ros_vision::Filter const> FilterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_vision::Filter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_vision::Filter_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'ros_vision': ['/home/capra/Ibex/src/ros_vision/msg', '/home/capra/Ibex/src/ros_vision/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_vision::Filter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_vision::Filter_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vision::Filter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vision::Filter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vision::Filter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vision::Filter_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_vision::Filter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55c82cbc203fb06b15cd95758e1e3024";
  }

  static const char* value(const ::ros_vision::Filter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55c82cbc203fb06bULL;
  static const uint64_t static_value2 = 0x15cd95758e1e3024ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_vision::Filter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_vision/Filter";
  }

  static const char* value(const ::ros_vision::Filter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_vision::Filter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
string type\n\
string description\n\
IODescriptor[] inputs\n\
IODescriptor[] outputs\n\
Parameter[] parameters\n\
\n\
================================================================================\n\
MSG: ros_vision/IODescriptor\n\
string name\n\
string topic\n\
string type\n\
================================================================================\n\
MSG: ros_vision/Parameter\n\
string name\n\
string description\n\
string type\n\
string default\n\
string min\n\
string max\n\
";
  }

  static const char* value(const ::ros_vision::Filter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_vision::Filter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.type);
      stream.next(m.description);
      stream.next(m.inputs);
      stream.next(m.outputs);
      stream.next(m.parameters);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Filter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_vision::Filter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_vision::Filter_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description);
    s << indent << "inputs[]" << std::endl;
    for (size_t i = 0; i < v.inputs.size(); ++i)
    {
      s << indent << "  inputs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_vision::IODescriptor_<ContainerAllocator> >::stream(s, indent + "    ", v.inputs[i]);
    }
    s << indent << "outputs[]" << std::endl;
    for (size_t i = 0; i < v.outputs.size(); ++i)
    {
      s << indent << "  outputs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_vision::IODescriptor_<ContainerAllocator> >::stream(s, indent + "    ", v.outputs[i]);
    }
    s << indent << "parameters[]" << std::endl;
    for (size_t i = 0; i < v.parameters.size(); ++i)
    {
      s << indent << "  parameters[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_vision::Parameter_<ContainerAllocator> >::stream(s, indent + "    ", v.parameters[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_VISION_MESSAGE_FILTER_H
