// Generated by gencpp from file ros_vision/GetParameterValue.msg
// DO NOT EDIT!


#ifndef ROS_VISION_MESSAGE_GETPARAMETERVALUE_H
#define ROS_VISION_MESSAGE_GETPARAMETERVALUE_H

#include <ros/service_traits.h>


#include <ros_vision/GetParameterValueRequest.h>
#include <ros_vision/GetParameterValueResponse.h>


namespace ros_vision
{

struct GetParameterValue
{

typedef GetParameterValueRequest Request;
typedef GetParameterValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetParameterValue
} // namespace ros_vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vision::GetParameterValue > {
  static const char* value()
  {
    return "c6989f480361a011a41108499b2febd0";
  }

  static const char* value(const ::ros_vision::GetParameterValue&) { return value(); }
};

template<>
struct DataType< ::ros_vision::GetParameterValue > {
  static const char* value()
  {
    return "ros_vision/GetParameterValue";
  }

  static const char* value(const ::ros_vision::GetParameterValue&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vision::GetParameterValueRequest> should match 
// service_traits::MD5Sum< ::ros_vision::GetParameterValue > 
template<>
struct MD5Sum< ::ros_vision::GetParameterValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::GetParameterValue >::value();
  }
  static const char* value(const ::ros_vision::GetParameterValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::GetParameterValueRequest> should match 
// service_traits::DataType< ::ros_vision::GetParameterValue > 
template<>
struct DataType< ::ros_vision::GetParameterValueRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vision::GetParameterValue >::value();
  }
  static const char* value(const ::ros_vision::GetParameterValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vision::GetParameterValueResponse> should match 
// service_traits::MD5Sum< ::ros_vision::GetParameterValue > 
template<>
struct MD5Sum< ::ros_vision::GetParameterValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::GetParameterValue >::value();
  }
  static const char* value(const ::ros_vision::GetParameterValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::GetParameterValueResponse> should match 
// service_traits::DataType< ::ros_vision::GetParameterValue > 
template<>
struct DataType< ::ros_vision::GetParameterValueResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vision::GetParameterValue >::value();
  }
  static const char* value(const ::ros_vision::GetParameterValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VISION_MESSAGE_GETPARAMETERVALUE_H
