// Generated by gencpp from file ros_vision/ListWorkspaces.msg
// DO NOT EDIT!


#ifndef ROS_VISION_MESSAGE_LISTWORKSPACES_H
#define ROS_VISION_MESSAGE_LISTWORKSPACES_H

#include <ros/service_traits.h>


#include <ros_vision/ListWorkspacesRequest.h>
#include <ros_vision/ListWorkspacesResponse.h>


namespace ros_vision
{

struct ListWorkspaces
{

typedef ListWorkspacesRequest Request;
typedef ListWorkspacesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListWorkspaces
} // namespace ros_vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vision::ListWorkspaces > {
  static const char* value()
  {
    return "8b36c598e23fd962676550874c6879f7";
  }

  static const char* value(const ::ros_vision::ListWorkspaces&) { return value(); }
};

template<>
struct DataType< ::ros_vision::ListWorkspaces > {
  static const char* value()
  {
    return "ros_vision/ListWorkspaces";
  }

  static const char* value(const ::ros_vision::ListWorkspaces&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vision::ListWorkspacesRequest> should match 
// service_traits::MD5Sum< ::ros_vision::ListWorkspaces > 
template<>
struct MD5Sum< ::ros_vision::ListWorkspacesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::ListWorkspaces >::value();
  }
  static const char* value(const ::ros_vision::ListWorkspacesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::ListWorkspacesRequest> should match 
// service_traits::DataType< ::ros_vision::ListWorkspaces > 
template<>
struct DataType< ::ros_vision::ListWorkspacesRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vision::ListWorkspaces >::value();
  }
  static const char* value(const ::ros_vision::ListWorkspacesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vision::ListWorkspacesResponse> should match 
// service_traits::MD5Sum< ::ros_vision::ListWorkspaces > 
template<>
struct MD5Sum< ::ros_vision::ListWorkspacesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::ListWorkspaces >::value();
  }
  static const char* value(const ::ros_vision::ListWorkspacesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::ListWorkspacesResponse> should match 
// service_traits::DataType< ::ros_vision::ListWorkspaces > 
template<>
struct DataType< ::ros_vision::ListWorkspacesResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vision::ListWorkspaces >::value();
  }
  static const char* value(const ::ros_vision::ListWorkspacesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VISION_MESSAGE_LISTWORKSPACES_H
