// Generated by gencpp from file ros_vision/ListFilterTypes.msg
// DO NOT EDIT!


#ifndef ROS_VISION_MESSAGE_LISTFILTERTYPES_H
#define ROS_VISION_MESSAGE_LISTFILTERTYPES_H

#include <ros/service_traits.h>


#include <ros_vision/ListFilterTypesRequest.h>
#include <ros_vision/ListFilterTypesResponse.h>


namespace ros_vision
{

struct ListFilterTypes
{

typedef ListFilterTypesRequest Request;
typedef ListFilterTypesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListFilterTypes
} // namespace ros_vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vision::ListFilterTypes > {
  static const char* value()
  {
    return "48ca7f8131dcc85f21cec2237f55b37d";
  }

  static const char* value(const ::ros_vision::ListFilterTypes&) { return value(); }
};

template<>
struct DataType< ::ros_vision::ListFilterTypes > {
  static const char* value()
  {
    return "ros_vision/ListFilterTypes";
  }

  static const char* value(const ::ros_vision::ListFilterTypes&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vision::ListFilterTypesRequest> should match 
// service_traits::MD5Sum< ::ros_vision::ListFilterTypes > 
template<>
struct MD5Sum< ::ros_vision::ListFilterTypesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::ListFilterTypes >::value();
  }
  static const char* value(const ::ros_vision::ListFilterTypesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::ListFilterTypesRequest> should match 
// service_traits::DataType< ::ros_vision::ListFilterTypes > 
template<>
struct DataType< ::ros_vision::ListFilterTypesRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vision::ListFilterTypes >::value();
  }
  static const char* value(const ::ros_vision::ListFilterTypesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vision::ListFilterTypesResponse> should match 
// service_traits::MD5Sum< ::ros_vision::ListFilterTypes > 
template<>
struct MD5Sum< ::ros_vision::ListFilterTypesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::ListFilterTypes >::value();
  }
  static const char* value(const ::ros_vision::ListFilterTypesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::ListFilterTypesResponse> should match 
// service_traits::DataType< ::ros_vision::ListFilterTypes > 
template<>
struct DataType< ::ros_vision::ListFilterTypesResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vision::ListFilterTypes >::value();
  }
  static const char* value(const ::ros_vision::ListFilterTypesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VISION_MESSAGE_LISTFILTERTYPES_H
