// Generated by gencpp from file ros_vision/ListWorkspacesResponse.msg
// DO NOT EDIT!


#ifndef ROS_VISION_MESSAGE_LISTWORKSPACESRESPONSE_H
#define ROS_VISION_MESSAGE_LISTWORKSPACESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_vision
{
template <class ContainerAllocator>
struct ListWorkspacesResponse_
{
  typedef ListWorkspacesResponse_<ContainerAllocator> Type;

  ListWorkspacesResponse_()
    : workspaces()  {
    }
  ListWorkspacesResponse_(const ContainerAllocator& _alloc)
    : workspaces(_alloc)  {
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _workspaces_type;
  _workspaces_type workspaces;




  typedef boost::shared_ptr< ::ros_vision::ListWorkspacesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_vision::ListWorkspacesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ListWorkspacesResponse_

typedef ::ros_vision::ListWorkspacesResponse_<std::allocator<void> > ListWorkspacesResponse;

typedef boost::shared_ptr< ::ros_vision::ListWorkspacesResponse > ListWorkspacesResponsePtr;
typedef boost::shared_ptr< ::ros_vision::ListWorkspacesResponse const> ListWorkspacesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_vision::ListWorkspacesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_vision::ListWorkspacesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'ros_vision': ['/home/capra/Ibex/src/ros_vision/msg', '/home/capra/Ibex/src/ros_vision/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_vision::ListWorkspacesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_vision::ListWorkspacesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vision::ListWorkspacesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vision::ListWorkspacesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vision::ListWorkspacesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vision::ListWorkspacesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_vision::ListWorkspacesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b36c598e23fd962676550874c6879f7";
  }

  static const char* value(const ::ros_vision::ListWorkspacesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b36c598e23fd962ULL;
  static const uint64_t static_value2 = 0x676550874c6879f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_vision::ListWorkspacesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_vision/ListWorkspacesResponse";
  }

  static const char* value(const ::ros_vision::ListWorkspacesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_vision::ListWorkspacesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] workspaces\n\
";
  }

  static const char* value(const ::ros_vision::ListWorkspacesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_vision::ListWorkspacesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.workspaces);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ListWorkspacesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_vision::ListWorkspacesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_vision::ListWorkspacesResponse_<ContainerAllocator>& v)
  {
    s << indent << "workspaces[]" << std::endl;
    for (size_t i = 0; i < v.workspaces.size(); ++i)
    {
      s << indent << "  workspaces[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.workspaces[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_VISION_MESSAGE_LISTWORKSPACESRESPONSE_H
