// Generated by gencpp from file ros_vision/LoadWorkspace.msg
// DO NOT EDIT!


#ifndef ROS_VISION_MESSAGE_LOADWORKSPACE_H
#define ROS_VISION_MESSAGE_LOADWORKSPACE_H

#include <ros/service_traits.h>


#include <ros_vision/LoadWorkspaceRequest.h>
#include <ros_vision/LoadWorkspaceResponse.h>


namespace ros_vision
{

struct LoadWorkspace
{

typedef LoadWorkspaceRequest Request;
typedef LoadWorkspaceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadWorkspace
} // namespace ros_vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vision::LoadWorkspace > {
  static const char* value()
  {
    return "b23106c960b24118a58dad42411ac73e";
  }

  static const char* value(const ::ros_vision::LoadWorkspace&) { return value(); }
};

template<>
struct DataType< ::ros_vision::LoadWorkspace > {
  static const char* value()
  {
    return "ros_vision/LoadWorkspace";
  }

  static const char* value(const ::ros_vision::LoadWorkspace&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vision::LoadWorkspaceRequest> should match 
// service_traits::MD5Sum< ::ros_vision::LoadWorkspace > 
template<>
struct MD5Sum< ::ros_vision::LoadWorkspaceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::LoadWorkspace >::value();
  }
  static const char* value(const ::ros_vision::LoadWorkspaceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::LoadWorkspaceRequest> should match 
// service_traits::DataType< ::ros_vision::LoadWorkspace > 
template<>
struct DataType< ::ros_vision::LoadWorkspaceRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vision::LoadWorkspace >::value();
  }
  static const char* value(const ::ros_vision::LoadWorkspaceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vision::LoadWorkspaceResponse> should match 
// service_traits::MD5Sum< ::ros_vision::LoadWorkspace > 
template<>
struct MD5Sum< ::ros_vision::LoadWorkspaceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::LoadWorkspace >::value();
  }
  static const char* value(const ::ros_vision::LoadWorkspaceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::LoadWorkspaceResponse> should match 
// service_traits::DataType< ::ros_vision::LoadWorkspace > 
template<>
struct DataType< ::ros_vision::LoadWorkspaceResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vision::LoadWorkspace >::value();
  }
  static const char* value(const ::ros_vision::LoadWorkspaceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VISION_MESSAGE_LOADWORKSPACE_H
