// Generated by gencpp from file ros_vision/SaveWorkspace.msg
// DO NOT EDIT!


#ifndef ROS_VISION_MESSAGE_SAVEWORKSPACE_H
#define ROS_VISION_MESSAGE_SAVEWORKSPACE_H

#include <ros/service_traits.h>


#include <ros_vision/SaveWorkspaceRequest.h>
#include <ros_vision/SaveWorkspaceResponse.h>


namespace ros_vision
{

struct SaveWorkspace
{

typedef SaveWorkspaceRequest Request;
typedef SaveWorkspaceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveWorkspace
} // namespace ros_vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vision::SaveWorkspace > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::ros_vision::SaveWorkspace&) { return value(); }
};

template<>
struct DataType< ::ros_vision::SaveWorkspace > {
  static const char* value()
  {
    return "ros_vision/SaveWorkspace";
  }

  static const char* value(const ::ros_vision::SaveWorkspace&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vision::SaveWorkspaceRequest> should match 
// service_traits::MD5Sum< ::ros_vision::SaveWorkspace > 
template<>
struct MD5Sum< ::ros_vision::SaveWorkspaceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::SaveWorkspace >::value();
  }
  static const char* value(const ::ros_vision::SaveWorkspaceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::SaveWorkspaceRequest> should match 
// service_traits::DataType< ::ros_vision::SaveWorkspace > 
template<>
struct DataType< ::ros_vision::SaveWorkspaceRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vision::SaveWorkspace >::value();
  }
  static const char* value(const ::ros_vision::SaveWorkspaceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vision::SaveWorkspaceResponse> should match 
// service_traits::MD5Sum< ::ros_vision::SaveWorkspace > 
template<>
struct MD5Sum< ::ros_vision::SaveWorkspaceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::SaveWorkspace >::value();
  }
  static const char* value(const ::ros_vision::SaveWorkspaceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::SaveWorkspaceResponse> should match 
// service_traits::DataType< ::ros_vision::SaveWorkspace > 
template<>
struct DataType< ::ros_vision::SaveWorkspaceResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vision::SaveWorkspace >::value();
  }
  static const char* value(const ::ros_vision::SaveWorkspaceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VISION_MESSAGE_SAVEWORKSPACE_H
