// Generated by gencpp from file ros_vision/SetParameterValue.msg
// DO NOT EDIT!


#ifndef ROS_VISION_MESSAGE_SETPARAMETERVALUE_H
#define ROS_VISION_MESSAGE_SETPARAMETERVALUE_H

#include <ros/service_traits.h>


#include <ros_vision/SetParameterValueRequest.h>
#include <ros_vision/SetParameterValueResponse.h>


namespace ros_vision
{

struct SetParameterValue
{

typedef SetParameterValueRequest Request;
typedef SetParameterValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetParameterValue
} // namespace ros_vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_vision::SetParameterValue > {
  static const char* value()
  {
    return "9dfb3622c3b8f3307e6b9b3b516248ca";
  }

  static const char* value(const ::ros_vision::SetParameterValue&) { return value(); }
};

template<>
struct DataType< ::ros_vision::SetParameterValue > {
  static const char* value()
  {
    return "ros_vision/SetParameterValue";
  }

  static const char* value(const ::ros_vision::SetParameterValue&) { return value(); }
};


// service_traits::MD5Sum< ::ros_vision::SetParameterValueRequest> should match 
// service_traits::MD5Sum< ::ros_vision::SetParameterValue > 
template<>
struct MD5Sum< ::ros_vision::SetParameterValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::SetParameterValue >::value();
  }
  static const char* value(const ::ros_vision::SetParameterValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::SetParameterValueRequest> should match 
// service_traits::DataType< ::ros_vision::SetParameterValue > 
template<>
struct DataType< ::ros_vision::SetParameterValueRequest>
{
  static const char* value()
  {
    return DataType< ::ros_vision::SetParameterValue >::value();
  }
  static const char* value(const ::ros_vision::SetParameterValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_vision::SetParameterValueResponse> should match 
// service_traits::MD5Sum< ::ros_vision::SetParameterValue > 
template<>
struct MD5Sum< ::ros_vision::SetParameterValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_vision::SetParameterValue >::value();
  }
  static const char* value(const ::ros_vision::SetParameterValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_vision::SetParameterValueResponse> should match 
// service_traits::DataType< ::ros_vision::SetParameterValue > 
template<>
struct DataType< ::ros_vision::SetParameterValueResponse>
{
  static const char* value()
  {
    return DataType< ::ros_vision::SetParameterValue >::value();
  }
  static const char* value(const ::ros_vision::SetParameterValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_VISION_MESSAGE_SETPARAMETERVALUE_H
