// Generated by gencpp from file ros_vision/Statistics.msg
// DO NOT EDIT!


#ifndef ROS_VISION_MESSAGE_STATISTICS_H
#define ROS_VISION_MESSAGE_STATISTICS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ros_vision/FilterStatistics.h>

namespace ros_vision
{
template <class ContainerAllocator>
struct Statistics_
{
  typedef Statistics_<ContainerAllocator> Type;

  Statistics_()
    : average_execution_time(0.0)
    , filters()  {
    }
  Statistics_(const ContainerAllocator& _alloc)
    : average_execution_time(0.0)
    , filters(_alloc)  {
    }



   typedef float _average_execution_time_type;
  _average_execution_time_type average_execution_time;

   typedef std::vector< ::ros_vision::FilterStatistics_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ros_vision::FilterStatistics_<ContainerAllocator> >::other >  _filters_type;
  _filters_type filters;




  typedef boost::shared_ptr< ::ros_vision::Statistics_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_vision::Statistics_<ContainerAllocator> const> ConstPtr;

}; // struct Statistics_

typedef ::ros_vision::Statistics_<std::allocator<void> > Statistics;

typedef boost::shared_ptr< ::ros_vision::Statistics > StatisticsPtr;
typedef boost::shared_ptr< ::ros_vision::Statistics const> StatisticsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_vision::Statistics_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_vision::Statistics_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'ros_vision': ['/home/capra/Ibex/src/ros_vision/msg', '/home/capra/Ibex/src/ros_vision/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_vision::Statistics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_vision::Statistics_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vision::Statistics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_vision::Statistics_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vision::Statistics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_vision::Statistics_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_vision::Statistics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf5006a109010ce73134497d95c76257";
  }

  static const char* value(const ::ros_vision::Statistics_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf5006a109010ce7ULL;
  static const uint64_t static_value2 = 0x3134497d95c76257ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_vision::Statistics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_vision/Statistics";
  }

  static const char* value(const ::ros_vision::Statistics_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_vision::Statistics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 average_execution_time\n\
FilterStatistics[] filters\n\
================================================================================\n\
MSG: ros_vision/FilterStatistics\n\
string name\n\
float32 average_execution_time\n\
float32 last_execution_time\n\
";
  }

  static const char* value(const ::ros_vision::Statistics_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_vision::Statistics_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.average_execution_time);
      stream.next(m.filters);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Statistics_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_vision::Statistics_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_vision::Statistics_<ContainerAllocator>& v)
  {
    s << indent << "average_execution_time: ";
    Printer<float>::stream(s, indent + "  ", v.average_execution_time);
    s << indent << "filters[]" << std::endl;
    for (size_t i = 0; i < v.filters.size(); ++i)
    {
      s << indent << "  filters[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_vision::FilterStatistics_<ContainerAllocator> >::stream(s, indent + "    ", v.filters[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_VISION_MESSAGE_STATISTICS_H
