set(_CATKIN_CURRENT_PACKAGE "capra_demos")
set(capra_demos_MAINTAINER "mathieu <mathieu@todo.todo>")
set(capra_demos_DEPRECATED "")
set(capra_demos_VERSION "0.0.0")
set(capra_demos_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(capra_demos_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(capra_demos_BUILDTOOL_DEPENDS "catkin")