(cl:defpackage capra_ai-srv
  (:use )
  (:export
   "CLEARGOALLIST"
   "<CLEARGOALLIST-REQUEST>"
   "CLEARGOALLIST-REQUEST"
   "<CLEARGOALLIST-RESPONSE>"
   "CLEARGOALLIST-RESPONSE"
   "ADDGOAL"
   "<ADDGOAL-REQUEST>"
   "ADDGOAL-REQUEST"
   "<ADDGOAL-RESPONSE>"
   "ADDGOAL-RESPONSE"
   "CANCELGOAL"
   "<CANCELGOAL-REQUEST>"
   "CANCELGOAL-REQUEST"
   "<CANCELGOAL-RESPONSE>"
   "CANCELGOAL-RESPONSE"
  ))

