// Generated by gencpp from file seagoatvision_ros/ShowGuiRequest.msg
// DO NOT EDIT!


#ifndef SEAGOATVISION_ROS_MESSAGE_SHOWGUIREQUEST_H
#define SEAGOATVISION_ROS_MESSAGE_SHOWGUIREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace seagoatvision_ros
{
template <class ContainerAllocator>
struct ShowGuiRequest_
{
  typedef ShowGuiRequest_<ContainerAllocator> Type;

  ShowGuiRequest_()
    {
    }
  ShowGuiRequest_(const ContainerAllocator& _alloc)
    {
    }






  typedef boost::shared_ptr< ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ShowGuiRequest_

typedef ::seagoatvision_ros::ShowGuiRequest_<std::allocator<void> > ShowGuiRequest;

typedef boost::shared_ptr< ::seagoatvision_ros::ShowGuiRequest > ShowGuiRequestPtr;
typedef boost::shared_ptr< ::seagoatvision_ros::ShowGuiRequest const> ShowGuiRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace seagoatvision_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seagoatvision_ros/ShowGuiRequest";
  }

  static const char* value(const ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ShowGuiRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::seagoatvision_ros::ShowGuiRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SEAGOATVISION_ROS_MESSAGE_SHOWGUIREQUEST_H
