set(_CATKIN_CURRENT_PACKAGE "capra_controlpanel")
set(capra_controlpanel_MAINTAINER "yohan <yohan@todo.todo>")
set(capra_controlpanel_DEPRECATED "")
set(capra_controlpanel_VERSION "0.0.0")
set(capra_controlpanel_BUILD_DEPENDS "message_generation")
set(capra_controlpanel_RUN_DEPENDS "message_runtime")
set(capra_controlpanel_BUILDTOOL_DEPENDS "catkin")