set(_CATKIN_CURRENT_PACKAGE "capra_filters")
set(capra_filters_MAINTAINER "capra <capra@todo.todo>")
set(capra_filters_DEPRECATED "")
set(capra_filters_VERSION "0.0.0")
set(capra_filters_BUILD_DEPENDS "nodelet" "dynamic_reconfigure" "cv_bridge" "image_transport" "message_runtime")
set(capra_filters_RUN_DEPENDS "nodelet" "dynamic_reconfigure" "cv_bridge" "image_transport" "message_runtime")
set(capra_filters_BUILDTOOL_DEPENDS "catkin")