set(_CATKIN_CURRENT_PACKAGE "capra_gazebo")
set(capra_gazebo_MAINTAINER "jonathan <jonathan@todo.todo>")
set(capra_gazebo_DEPRECATED "")
set(capra_gazebo_VERSION "0.0.0")
set(capra_gazebo_BUILD_DEPENDS )
set(capra_gazebo_RUN_DEPENDS )
set(capra_gazebo_BUILDTOOL_DEPENDS "catkin")