// Generated by gencpp from file capra_msgs/AddGoal.msg
// DO NOT EDIT!


#ifndef CAPRA_MSGS_MESSAGE_ADDGOAL_H
#define CAPRA_MSGS_MESSAGE_ADDGOAL_H

#include <ros/service_traits.h>


#include <capra_msgs/AddGoalRequest.h>
#include <capra_msgs/AddGoalResponse.h>


namespace capra_msgs
{

struct AddGoal
{

typedef AddGoalRequest Request;
typedef AddGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddGoal
} // namespace capra_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::capra_msgs::AddGoal > {
  static const char* value()
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const ::capra_msgs::AddGoal&) { return value(); }
};

template<>
struct DataType< ::capra_msgs::AddGoal > {
  static const char* value()
  {
    return "capra_msgs/AddGoal";
  }

  static const char* value(const ::capra_msgs::AddGoal&) { return value(); }
};


// service_traits::MD5Sum< ::capra_msgs::AddGoalRequest> should match 
// service_traits::MD5Sum< ::capra_msgs::AddGoal > 
template<>
struct MD5Sum< ::capra_msgs::AddGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::capra_msgs::AddGoal >::value();
  }
  static const char* value(const ::capra_msgs::AddGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_msgs::AddGoalRequest> should match 
// service_traits::DataType< ::capra_msgs::AddGoal > 
template<>
struct DataType< ::capra_msgs::AddGoalRequest>
{
  static const char* value()
  {
    return DataType< ::capra_msgs::AddGoal >::value();
  }
  static const char* value(const ::capra_msgs::AddGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::capra_msgs::AddGoalResponse> should match 
// service_traits::MD5Sum< ::capra_msgs::AddGoal > 
template<>
struct MD5Sum< ::capra_msgs::AddGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::capra_msgs::AddGoal >::value();
  }
  static const char* value(const ::capra_msgs::AddGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_msgs::AddGoalResponse> should match 
// service_traits::DataType< ::capra_msgs::AddGoal > 
template<>
struct DataType< ::capra_msgs::AddGoalResponse>
{
  static const char* value()
  {
    return DataType< ::capra_msgs::AddGoal >::value();
  }
  static const char* value(const ::capra_msgs::AddGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAPRA_MSGS_MESSAGE_ADDGOAL_H
