// Generated by gencpp from file capra_msgs/AiStatus.msg
// DO NOT EDIT!


#ifndef CAPRA_MSGS_MESSAGE_AISTATUS_H
#define CAPRA_MSGS_MESSAGE_AISTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace capra_msgs
{
template <class ContainerAllocator>
struct AiStatus_
{
  typedef AiStatus_<ContainerAllocator> Type;

  AiStatus_()
    : isRunning(false)  {
    }
  AiStatus_(const ContainerAllocator& _alloc)
    : isRunning(false)  {
    }



   typedef uint8_t _isRunning_type;
  _isRunning_type isRunning;




  typedef boost::shared_ptr< ::capra_msgs::AiStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::capra_msgs::AiStatus_<ContainerAllocator> const> ConstPtr;

}; // struct AiStatus_

typedef ::capra_msgs::AiStatus_<std::allocator<void> > AiStatus;

typedef boost::shared_ptr< ::capra_msgs::AiStatus > AiStatusPtr;
typedef boost::shared_ptr< ::capra_msgs::AiStatus const> AiStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::capra_msgs::AiStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::capra_msgs::AiStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace capra_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'capra_msgs': ['/home/capra/Ibex/src/capra_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::capra_msgs::AiStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::capra_msgs::AiStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capra_msgs::AiStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capra_msgs::AiStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capra_msgs::AiStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capra_msgs::AiStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::capra_msgs::AiStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2d5194b33b82502361bdb80f0070282";
  }

  static const char* value(const ::capra_msgs::AiStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2d5194b33b82502ULL;
  static const uint64_t static_value2 = 0x361bdb80f0070282ULL;
};

template<class ContainerAllocator>
struct DataType< ::capra_msgs::AiStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "capra_msgs/AiStatus";
  }

  static const char* value(const ::capra_msgs::AiStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::capra_msgs::AiStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isRunning\n\
";
  }

  static const char* value(const ::capra_msgs::AiStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::capra_msgs::AiStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isRunning);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AiStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::capra_msgs::AiStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::capra_msgs::AiStatus_<ContainerAllocator>& v)
  {
    s << indent << "isRunning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isRunning);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAPRA_MSGS_MESSAGE_AISTATUS_H
