// Generated by gencpp from file capra_msgs/CollectHardIronFieldCalibrationData.msg
// DO NOT EDIT!


#ifndef CAPRA_MSGS_MESSAGE_COLLECTHARDIRONFIELDCALIBRATIONDATA_H
#define CAPRA_MSGS_MESSAGE_COLLECTHARDIRONFIELDCALIBRATIONDATA_H

#include <ros/service_traits.h>


#include <capra_msgs/CollectHardIronFieldCalibrationDataRequest.h>
#include <capra_msgs/CollectHardIronFieldCalibrationDataResponse.h>


namespace capra_msgs
{

struct CollectHardIronFieldCalibrationData
{

typedef CollectHardIronFieldCalibrationDataRequest Request;
typedef CollectHardIronFieldCalibrationDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CollectHardIronFieldCalibrationData
} // namespace capra_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::capra_msgs::CollectHardIronFieldCalibrationData > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::capra_msgs::CollectHardIronFieldCalibrationData&) { return value(); }
};

template<>
struct DataType< ::capra_msgs::CollectHardIronFieldCalibrationData > {
  static const char* value()
  {
    return "capra_msgs/CollectHardIronFieldCalibrationData";
  }

  static const char* value(const ::capra_msgs::CollectHardIronFieldCalibrationData&) { return value(); }
};


// service_traits::MD5Sum< ::capra_msgs::CollectHardIronFieldCalibrationDataRequest> should match 
// service_traits::MD5Sum< ::capra_msgs::CollectHardIronFieldCalibrationData > 
template<>
struct MD5Sum< ::capra_msgs::CollectHardIronFieldCalibrationDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::capra_msgs::CollectHardIronFieldCalibrationData >::value();
  }
  static const char* value(const ::capra_msgs::CollectHardIronFieldCalibrationDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_msgs::CollectHardIronFieldCalibrationDataRequest> should match 
// service_traits::DataType< ::capra_msgs::CollectHardIronFieldCalibrationData > 
template<>
struct DataType< ::capra_msgs::CollectHardIronFieldCalibrationDataRequest>
{
  static const char* value()
  {
    return DataType< ::capra_msgs::CollectHardIronFieldCalibrationData >::value();
  }
  static const char* value(const ::capra_msgs::CollectHardIronFieldCalibrationDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::capra_msgs::CollectHardIronFieldCalibrationDataResponse> should match 
// service_traits::MD5Sum< ::capra_msgs::CollectHardIronFieldCalibrationData > 
template<>
struct MD5Sum< ::capra_msgs::CollectHardIronFieldCalibrationDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::capra_msgs::CollectHardIronFieldCalibrationData >::value();
  }
  static const char* value(const ::capra_msgs::CollectHardIronFieldCalibrationDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_msgs::CollectHardIronFieldCalibrationDataResponse> should match 
// service_traits::DataType< ::capra_msgs::CollectHardIronFieldCalibrationData > 
template<>
struct DataType< ::capra_msgs::CollectHardIronFieldCalibrationDataResponse>
{
  static const char* value()
  {
    return DataType< ::capra_msgs::CollectHardIronFieldCalibrationData >::value();
  }
  static const char* value(const ::capra_msgs::CollectHardIronFieldCalibrationDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAPRA_MSGS_MESSAGE_COLLECTHARDIRONFIELDCALIBRATIONDATA_H
