// Generated by gencpp from file capra_msgs/ComputeHardIronFieldCalibration.msg
// DO NOT EDIT!


#ifndef CAPRA_MSGS_MESSAGE_COMPUTEHARDIRONFIELDCALIBRATION_H
#define CAPRA_MSGS_MESSAGE_COMPUTEHARDIRONFIELDCALIBRATION_H

#include <ros/service_traits.h>


#include <capra_msgs/ComputeHardIronFieldCalibrationRequest.h>
#include <capra_msgs/ComputeHardIronFieldCalibrationResponse.h>


namespace capra_msgs
{

struct ComputeHardIronFieldCalibration
{

typedef ComputeHardIronFieldCalibrationRequest Request;
typedef ComputeHardIronFieldCalibrationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ComputeHardIronFieldCalibration
} // namespace capra_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::capra_msgs::ComputeHardIronFieldCalibration > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::capra_msgs::ComputeHardIronFieldCalibration&) { return value(); }
};

template<>
struct DataType< ::capra_msgs::ComputeHardIronFieldCalibration > {
  static const char* value()
  {
    return "capra_msgs/ComputeHardIronFieldCalibration";
  }

  static const char* value(const ::capra_msgs::ComputeHardIronFieldCalibration&) { return value(); }
};


// service_traits::MD5Sum< ::capra_msgs::ComputeHardIronFieldCalibrationRequest> should match 
// service_traits::MD5Sum< ::capra_msgs::ComputeHardIronFieldCalibration > 
template<>
struct MD5Sum< ::capra_msgs::ComputeHardIronFieldCalibrationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::capra_msgs::ComputeHardIronFieldCalibration >::value();
  }
  static const char* value(const ::capra_msgs::ComputeHardIronFieldCalibrationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_msgs::ComputeHardIronFieldCalibrationRequest> should match 
// service_traits::DataType< ::capra_msgs::ComputeHardIronFieldCalibration > 
template<>
struct DataType< ::capra_msgs::ComputeHardIronFieldCalibrationRequest>
{
  static const char* value()
  {
    return DataType< ::capra_msgs::ComputeHardIronFieldCalibration >::value();
  }
  static const char* value(const ::capra_msgs::ComputeHardIronFieldCalibrationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::capra_msgs::ComputeHardIronFieldCalibrationResponse> should match 
// service_traits::MD5Sum< ::capra_msgs::ComputeHardIronFieldCalibration > 
template<>
struct MD5Sum< ::capra_msgs::ComputeHardIronFieldCalibrationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::capra_msgs::ComputeHardIronFieldCalibration >::value();
  }
  static const char* value(const ::capra_msgs::ComputeHardIronFieldCalibrationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_msgs::ComputeHardIronFieldCalibrationResponse> should match 
// service_traits::DataType< ::capra_msgs::ComputeHardIronFieldCalibration > 
template<>
struct DataType< ::capra_msgs::ComputeHardIronFieldCalibrationResponse>
{
  static const char* value()
  {
    return DataType< ::capra_msgs::ComputeHardIronFieldCalibration >::value();
  }
  static const char* value(const ::capra_msgs::ComputeHardIronFieldCalibrationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAPRA_MSGS_MESSAGE_COMPUTEHARDIRONFIELDCALIBRATION_H
