// Generated by gencpp from file capra_msgs/ResetPosition.msg
// DO NOT EDIT!


#ifndef CAPRA_MSGS_MESSAGE_RESETPOSITION_H
#define CAPRA_MSGS_MESSAGE_RESETPOSITION_H

#include <ros/service_traits.h>


#include <capra_msgs/ResetPositionRequest.h>
#include <capra_msgs/ResetPositionResponse.h>


namespace capra_msgs
{

struct ResetPosition
{

typedef ResetPositionRequest Request;
typedef ResetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetPosition
} // namespace capra_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::capra_msgs::ResetPosition > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::capra_msgs::ResetPosition&) { return value(); }
};

template<>
struct DataType< ::capra_msgs::ResetPosition > {
  static const char* value()
  {
    return "capra_msgs/ResetPosition";
  }

  static const char* value(const ::capra_msgs::ResetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::capra_msgs::ResetPositionRequest> should match 
// service_traits::MD5Sum< ::capra_msgs::ResetPosition > 
template<>
struct MD5Sum< ::capra_msgs::ResetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::capra_msgs::ResetPosition >::value();
  }
  static const char* value(const ::capra_msgs::ResetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_msgs::ResetPositionRequest> should match 
// service_traits::DataType< ::capra_msgs::ResetPosition > 
template<>
struct DataType< ::capra_msgs::ResetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::capra_msgs::ResetPosition >::value();
  }
  static const char* value(const ::capra_msgs::ResetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::capra_msgs::ResetPositionResponse> should match 
// service_traits::MD5Sum< ::capra_msgs::ResetPosition > 
template<>
struct MD5Sum< ::capra_msgs::ResetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::capra_msgs::ResetPosition >::value();
  }
  static const char* value(const ::capra_msgs::ResetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_msgs::ResetPositionResponse> should match 
// service_traits::DataType< ::capra_msgs::ResetPosition > 
template<>
struct DataType< ::capra_msgs::ResetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::capra_msgs::ResetPosition >::value();
  }
  static const char* value(const ::capra_msgs::ResetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAPRA_MSGS_MESSAGE_RESETPOSITION_H
