// Generated by gencpp from file capra_msgs/SetWheelSpeedRequest.msg
// DO NOT EDIT!


#ifndef CAPRA_MSGS_MESSAGE_SETWHEELSPEEDREQUEST_H
#define CAPRA_MSGS_MESSAGE_SETWHEELSPEEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace capra_msgs
{
template <class ContainerAllocator>
struct SetWheelSpeedRequest_
{
  typedef SetWheelSpeedRequest_<ContainerAllocator> Type;

  SetWheelSpeedRequest_()
    : wheel(0)
    , speed(0.0)  {
    }
  SetWheelSpeedRequest_(const ContainerAllocator& _alloc)
    : wheel(0)
    , speed(0.0)  {
    }



   typedef int8_t _wheel_type;
  _wheel_type wheel;

   typedef float _speed_type;
  _speed_type speed;




  typedef boost::shared_ptr< ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetWheelSpeedRequest_

typedef ::capra_msgs::SetWheelSpeedRequest_<std::allocator<void> > SetWheelSpeedRequest;

typedef boost::shared_ptr< ::capra_msgs::SetWheelSpeedRequest > SetWheelSpeedRequestPtr;
typedef boost::shared_ptr< ::capra_msgs::SetWheelSpeedRequest const> SetWheelSpeedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace capra_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'capra_msgs': ['/home/capra/Ibex/src/capra_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "812356feddcdc2f447f0699a2c1e2105";
  }

  static const char* value(const ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x812356feddcdc2f4ULL;
  static const uint64_t static_value2 = 0x47f0699a2c1e2105ULL;
};

template<class ContainerAllocator>
struct DataType< ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "capra_msgs/SetWheelSpeedRequest";
  }

  static const char* value(const ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 wheel\n\
float32 speed\n\
";
  }

  static const char* value(const ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wheel);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetWheelSpeedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::capra_msgs::SetWheelSpeedRequest_<ContainerAllocator>& v)
  {
    s << indent << "wheel: ";
    Printer<int8_t>::stream(s, indent + "  ", v.wheel);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAPRA_MSGS_MESSAGE_SETWHEELSPEEDREQUEST_H
