// Generated by gencpp from file capra_msgs/StartAcquisition.msg
// DO NOT EDIT!


#ifndef CAPRA_MSGS_MESSAGE_STARTACQUISITION_H
#define CAPRA_MSGS_MESSAGE_STARTACQUISITION_H

#include <ros/service_traits.h>


#include <capra_msgs/StartAcquisitionRequest.h>
#include <capra_msgs/StartAcquisitionResponse.h>


namespace capra_msgs
{

struct StartAcquisition
{

typedef StartAcquisitionRequest Request;
typedef StartAcquisitionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartAcquisition
} // namespace capra_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::capra_msgs::StartAcquisition > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::capra_msgs::StartAcquisition&) { return value(); }
};

template<>
struct DataType< ::capra_msgs::StartAcquisition > {
  static const char* value()
  {
    return "capra_msgs/StartAcquisition";
  }

  static const char* value(const ::capra_msgs::StartAcquisition&) { return value(); }
};


// service_traits::MD5Sum< ::capra_msgs::StartAcquisitionRequest> should match 
// service_traits::MD5Sum< ::capra_msgs::StartAcquisition > 
template<>
struct MD5Sum< ::capra_msgs::StartAcquisitionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::capra_msgs::StartAcquisition >::value();
  }
  static const char* value(const ::capra_msgs::StartAcquisitionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_msgs::StartAcquisitionRequest> should match 
// service_traits::DataType< ::capra_msgs::StartAcquisition > 
template<>
struct DataType< ::capra_msgs::StartAcquisitionRequest>
{
  static const char* value()
  {
    return DataType< ::capra_msgs::StartAcquisition >::value();
  }
  static const char* value(const ::capra_msgs::StartAcquisitionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::capra_msgs::StartAcquisitionResponse> should match 
// service_traits::MD5Sum< ::capra_msgs::StartAcquisition > 
template<>
struct MD5Sum< ::capra_msgs::StartAcquisitionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::capra_msgs::StartAcquisition >::value();
  }
  static const char* value(const ::capra_msgs::StartAcquisitionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_msgs::StartAcquisitionResponse> should match 
// service_traits::DataType< ::capra_msgs::StartAcquisition > 
template<>
struct DataType< ::capra_msgs::StartAcquisitionResponse>
{
  static const char* value()
  {
    return DataType< ::capra_msgs::StartAcquisition >::value();
  }
  static const char* value(const ::capra_msgs::StartAcquisitionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAPRA_MSGS_MESSAGE_STARTACQUISITION_H
