// Generated by gencpp from file capra_msgs/StopAcquisition.msg
// DO NOT EDIT!


#ifndef CAPRA_MSGS_MESSAGE_STOPACQUISITION_H
#define CAPRA_MSGS_MESSAGE_STOPACQUISITION_H

#include <ros/service_traits.h>


#include <capra_msgs/StopAcquisitionRequest.h>
#include <capra_msgs/StopAcquisitionResponse.h>


namespace capra_msgs
{

struct StopAcquisition
{

typedef StopAcquisitionRequest Request;
typedef StopAcquisitionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopAcquisition
} // namespace capra_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::capra_msgs::StopAcquisition > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::capra_msgs::StopAcquisition&) { return value(); }
};

template<>
struct DataType< ::capra_msgs::StopAcquisition > {
  static const char* value()
  {
    return "capra_msgs/StopAcquisition";
  }

  static const char* value(const ::capra_msgs::StopAcquisition&) { return value(); }
};


// service_traits::MD5Sum< ::capra_msgs::StopAcquisitionRequest> should match 
// service_traits::MD5Sum< ::capra_msgs::StopAcquisition > 
template<>
struct MD5Sum< ::capra_msgs::StopAcquisitionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::capra_msgs::StopAcquisition >::value();
  }
  static const char* value(const ::capra_msgs::StopAcquisitionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_msgs::StopAcquisitionRequest> should match 
// service_traits::DataType< ::capra_msgs::StopAcquisition > 
template<>
struct DataType< ::capra_msgs::StopAcquisitionRequest>
{
  static const char* value()
  {
    return DataType< ::capra_msgs::StopAcquisition >::value();
  }
  static const char* value(const ::capra_msgs::StopAcquisitionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::capra_msgs::StopAcquisitionResponse> should match 
// service_traits::MD5Sum< ::capra_msgs::StopAcquisition > 
template<>
struct MD5Sum< ::capra_msgs::StopAcquisitionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::capra_msgs::StopAcquisition >::value();
  }
  static const char* value(const ::capra_msgs::StopAcquisitionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_msgs::StopAcquisitionResponse> should match 
// service_traits::DataType< ::capra_msgs::StopAcquisition > 
template<>
struct DataType< ::capra_msgs::StopAcquisitionResponse>
{
  static const char* value()
  {
    return DataType< ::capra_msgs::StopAcquisition >::value();
  }
  static const char* value(const ::capra_msgs::StopAcquisitionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAPRA_MSGS_MESSAGE_STOPACQUISITION_H
