// Generated by gencpp from file capra_msgs/ToggleLightRequest.msg
// DO NOT EDIT!


#ifndef CAPRA_MSGS_MESSAGE_TOGGLELIGHTREQUEST_H
#define CAPRA_MSGS_MESSAGE_TOGGLELIGHTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace capra_msgs
{
template <class ContainerAllocator>
struct ToggleLightRequest_
{
  typedef ToggleLightRequest_<ContainerAllocator> Type;

  ToggleLightRequest_()
    : on(false)  {
    }
  ToggleLightRequest_(const ContainerAllocator& _alloc)
    : on(false)  {
    }



   typedef uint8_t _on_type;
  _on_type on;




  typedef boost::shared_ptr< ::capra_msgs::ToggleLightRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::capra_msgs::ToggleLightRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ToggleLightRequest_

typedef ::capra_msgs::ToggleLightRequest_<std::allocator<void> > ToggleLightRequest;

typedef boost::shared_ptr< ::capra_msgs::ToggleLightRequest > ToggleLightRequestPtr;
typedef boost::shared_ptr< ::capra_msgs::ToggleLightRequest const> ToggleLightRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::capra_msgs::ToggleLightRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::capra_msgs::ToggleLightRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace capra_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'capra_msgs': ['/home/capra/Ibex/src/capra_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::capra_msgs::ToggleLightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::capra_msgs::ToggleLightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capra_msgs::ToggleLightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capra_msgs::ToggleLightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capra_msgs::ToggleLightRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capra_msgs::ToggleLightRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::capra_msgs::ToggleLightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74983d2ffe4877de8ae30b7a94625c41";
  }

  static const char* value(const ::capra_msgs::ToggleLightRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74983d2ffe4877deULL;
  static const uint64_t static_value2 = 0x8ae30b7a94625c41ULL;
};

template<class ContainerAllocator>
struct DataType< ::capra_msgs::ToggleLightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "capra_msgs/ToggleLightRequest";
  }

  static const char* value(const ::capra_msgs::ToggleLightRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::capra_msgs::ToggleLightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool on\n\
";
  }

  static const char* value(const ::capra_msgs::ToggleLightRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::capra_msgs::ToggleLightRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.on);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ToggleLightRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::capra_msgs::ToggleLightRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::capra_msgs::ToggleLightRequest_<ContainerAllocator>& v)
  {
    s << indent << "on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.on);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAPRA_MSGS_MESSAGE_TOGGLELIGHTREQUEST_H
