// Generated by gencpp from file capra_msgs/ToggleLight.msg
// DO NOT EDIT!


#ifndef CAPRA_MSGS_MESSAGE_TOGGLELIGHT_H
#define CAPRA_MSGS_MESSAGE_TOGGLELIGHT_H

#include <ros/service_traits.h>


#include <capra_msgs/ToggleLightRequest.h>
#include <capra_msgs/ToggleLightResponse.h>


namespace capra_msgs
{

struct ToggleLight
{

typedef ToggleLightRequest Request;
typedef ToggleLightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToggleLight
} // namespace capra_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::capra_msgs::ToggleLight > {
  static const char* value()
  {
    return "74983d2ffe4877de8ae30b7a94625c41";
  }

  static const char* value(const ::capra_msgs::ToggleLight&) { return value(); }
};

template<>
struct DataType< ::capra_msgs::ToggleLight > {
  static const char* value()
  {
    return "capra_msgs/ToggleLight";
  }

  static const char* value(const ::capra_msgs::ToggleLight&) { return value(); }
};


// service_traits::MD5Sum< ::capra_msgs::ToggleLightRequest> should match 
// service_traits::MD5Sum< ::capra_msgs::ToggleLight > 
template<>
struct MD5Sum< ::capra_msgs::ToggleLightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::capra_msgs::ToggleLight >::value();
  }
  static const char* value(const ::capra_msgs::ToggleLightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_msgs::ToggleLightRequest> should match 
// service_traits::DataType< ::capra_msgs::ToggleLight > 
template<>
struct DataType< ::capra_msgs::ToggleLightRequest>
{
  static const char* value()
  {
    return DataType< ::capra_msgs::ToggleLight >::value();
  }
  static const char* value(const ::capra_msgs::ToggleLightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::capra_msgs::ToggleLightResponse> should match 
// service_traits::MD5Sum< ::capra_msgs::ToggleLight > 
template<>
struct MD5Sum< ::capra_msgs::ToggleLightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::capra_msgs::ToggleLight >::value();
  }
  static const char* value(const ::capra_msgs::ToggleLightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_msgs::ToggleLightResponse> should match 
// service_traits::DataType< ::capra_msgs::ToggleLight > 
template<>
struct DataType< ::capra_msgs::ToggleLightResponse>
{
  static const char* value()
  {
    return DataType< ::capra_msgs::ToggleLight >::value();
  }
  static const char* value(const ::capra_msgs::ToggleLightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAPRA_MSGS_MESSAGE_TOGGLELIGHT_H
