// Generated by gencpp from file capra_ai/CancelGoal.msg
// DO NOT EDIT!


#ifndef CAPRA_AI_MESSAGE_CANCELGOAL_H
#define CAPRA_AI_MESSAGE_CANCELGOAL_H

#include <ros/service_traits.h>


#include <capra_ai/CancelGoalRequest.h>
#include <capra_ai/CancelGoalResponse.h>


namespace capra_ai
{

struct CancelGoal
{

typedef CancelGoalRequest Request;
typedef CancelGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CancelGoal
} // namespace capra_ai


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::capra_ai::CancelGoal > {
  static const char* value()
  {
    return "6d6dba85b2fd764127a311dd3aeaaf2f";
  }

  static const char* value(const ::capra_ai::CancelGoal&) { return value(); }
};

template<>
struct DataType< ::capra_ai::CancelGoal > {
  static const char* value()
  {
    return "capra_ai/CancelGoal";
  }

  static const char* value(const ::capra_ai::CancelGoal&) { return value(); }
};


// service_traits::MD5Sum< ::capra_ai::CancelGoalRequest> should match 
// service_traits::MD5Sum< ::capra_ai::CancelGoal > 
template<>
struct MD5Sum< ::capra_ai::CancelGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::capra_ai::CancelGoal >::value();
  }
  static const char* value(const ::capra_ai::CancelGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_ai::CancelGoalRequest> should match 
// service_traits::DataType< ::capra_ai::CancelGoal > 
template<>
struct DataType< ::capra_ai::CancelGoalRequest>
{
  static const char* value()
  {
    return DataType< ::capra_ai::CancelGoal >::value();
  }
  static const char* value(const ::capra_ai::CancelGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::capra_ai::CancelGoalResponse> should match 
// service_traits::MD5Sum< ::capra_ai::CancelGoal > 
template<>
struct MD5Sum< ::capra_ai::CancelGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::capra_ai::CancelGoal >::value();
  }
  static const char* value(const ::capra_ai::CancelGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_ai::CancelGoalResponse> should match 
// service_traits::DataType< ::capra_ai::CancelGoal > 
template<>
struct DataType< ::capra_ai::CancelGoalResponse>
{
  static const char* value()
  {
    return DataType< ::capra_ai::CancelGoal >::value();
  }
  static const char* value(const ::capra_ai::CancelGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAPRA_AI_MESSAGE_CANCELGOAL_H
