// Generated by gencpp from file capra_ai/ClearGoalList.msg
// DO NOT EDIT!


#ifndef CAPRA_AI_MESSAGE_CLEARGOALLIST_H
#define CAPRA_AI_MESSAGE_CLEARGOALLIST_H

#include <ros/service_traits.h>


#include <capra_ai/ClearGoalListRequest.h>
#include <capra_ai/ClearGoalListResponse.h>


namespace capra_ai
{

struct ClearGoalList
{

typedef ClearGoalListRequest Request;
typedef ClearGoalListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearGoalList
} // namespace capra_ai


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::capra_ai::ClearGoalList > {
  static const char* value()
  {
    return "19340f526e135109f7ccd6ab9f1ca72e";
  }

  static const char* value(const ::capra_ai::ClearGoalList&) { return value(); }
};

template<>
struct DataType< ::capra_ai::ClearGoalList > {
  static const char* value()
  {
    return "capra_ai/ClearGoalList";
  }

  static const char* value(const ::capra_ai::ClearGoalList&) { return value(); }
};


// service_traits::MD5Sum< ::capra_ai::ClearGoalListRequest> should match 
// service_traits::MD5Sum< ::capra_ai::ClearGoalList > 
template<>
struct MD5Sum< ::capra_ai::ClearGoalListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::capra_ai::ClearGoalList >::value();
  }
  static const char* value(const ::capra_ai::ClearGoalListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_ai::ClearGoalListRequest> should match 
// service_traits::DataType< ::capra_ai::ClearGoalList > 
template<>
struct DataType< ::capra_ai::ClearGoalListRequest>
{
  static const char* value()
  {
    return DataType< ::capra_ai::ClearGoalList >::value();
  }
  static const char* value(const ::capra_ai::ClearGoalListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::capra_ai::ClearGoalListResponse> should match 
// service_traits::MD5Sum< ::capra_ai::ClearGoalList > 
template<>
struct MD5Sum< ::capra_ai::ClearGoalListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::capra_ai::ClearGoalList >::value();
  }
  static const char* value(const ::capra_ai::ClearGoalListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_ai::ClearGoalListResponse> should match 
// service_traits::DataType< ::capra_ai::ClearGoalList > 
template<>
struct DataType< ::capra_ai::ClearGoalListResponse>
{
  static const char* value()
  {
    return DataType< ::capra_ai::ClearGoalList >::value();
  }
  static const char* value(const ::capra_ai::ClearGoalListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAPRA_AI_MESSAGE_CLEARGOALLIST_H
