// Generated by gencpp from file capra_ai/GoalWithPriority.msg
// DO NOT EDIT!


#ifndef CAPRA_AI_MESSAGE_GOALWITHPRIORITY_H
#define CAPRA_AI_MESSAGE_GOALWITHPRIORITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <actionlib_msgs/GoalID.h>
#include <geometry_msgs/Pose.h>

namespace capra_ai
{
template <class ContainerAllocator>
struct GoalWithPriority_
{
  typedef GoalWithPriority_<ContainerAllocator> Type;

  GoalWithPriority_()
    : goal_id()
    , pose()
    , priority(0)  {
    }
  GoalWithPriority_(const ContainerAllocator& _alloc)
    : goal_id(_alloc)
    , pose(_alloc)
    , priority(0)  {
    }



   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef uint32_t _priority_type;
  _priority_type priority;




  typedef boost::shared_ptr< ::capra_ai::GoalWithPriority_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::capra_ai::GoalWithPriority_<ContainerAllocator> const> ConstPtr;

}; // struct GoalWithPriority_

typedef ::capra_ai::GoalWithPriority_<std::allocator<void> > GoalWithPriority;

typedef boost::shared_ptr< ::capra_ai::GoalWithPriority > GoalWithPriorityPtr;
typedef boost::shared_ptr< ::capra_ai::GoalWithPriority const> GoalWithPriorityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::capra_ai::GoalWithPriority_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::capra_ai::GoalWithPriority_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace capra_ai

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'capra_msgs': ['/home/capra/Ibex/src/capra_msgs/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'capra_ai': ['/home/capra/Ibex/src/capra_ai/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::capra_ai::GoalWithPriority_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::capra_ai::GoalWithPriority_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capra_ai::GoalWithPriority_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capra_ai::GoalWithPriority_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capra_ai::GoalWithPriority_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capra_ai::GoalWithPriority_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::capra_ai::GoalWithPriority_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98ffe882d55a7727025836eac4535e75";
  }

  static const char* value(const ::capra_ai::GoalWithPriority_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98ffe882d55a7727ULL;
  static const uint64_t static_value2 = 0x025836eac4535e75ULL;
};

template<class ContainerAllocator>
struct DataType< ::capra_ai::GoalWithPriority_<ContainerAllocator> >
{
  static const char* value()
  {
    return "capra_ai/GoalWithPriority";
  }

  static const char* value(const ::capra_ai::GoalWithPriority_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::capra_ai::GoalWithPriority_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actionlib_msgs/GoalID goal_id\n\
geometry_msgs/Pose pose\n\
uint32 priority\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::capra_ai::GoalWithPriority_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::capra_ai::GoalWithPriority_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_id);
      stream.next(m.pose);
      stream.next(m.priority);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GoalWithPriority_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::capra_ai::GoalWithPriority_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::capra_ai::GoalWithPriority_<ContainerAllocator>& v)
  {
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "priority: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.priority);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAPRA_AI_MESSAGE_GOALWITHPRIORITY_H
