// Generated by gencpp from file animatics_smart_motor/MotorsConnected.msg
// DO NOT EDIT!


#ifndef ANIMATICS_SMART_MOTOR_MESSAGE_MOTORSCONNECTED_H
#define ANIMATICS_SMART_MOTOR_MESSAGE_MOTORSCONNECTED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace animatics_smart_motor
{
template <class ContainerAllocator>
struct MotorsConnected_
{
  typedef MotorsConnected_<ContainerAllocator> Type;

  MotorsConnected_()
    : connected(false)  {
    }
  MotorsConnected_(const ContainerAllocator& _alloc)
    : connected(false)  {
    }



   typedef uint8_t _connected_type;
  _connected_type connected;




  typedef boost::shared_ptr< ::animatics_smart_motor::MotorsConnected_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::animatics_smart_motor::MotorsConnected_<ContainerAllocator> const> ConstPtr;

}; // struct MotorsConnected_

typedef ::animatics_smart_motor::MotorsConnected_<std::allocator<void> > MotorsConnected;

typedef boost::shared_ptr< ::animatics_smart_motor::MotorsConnected > MotorsConnectedPtr;
typedef boost::shared_ptr< ::animatics_smart_motor::MotorsConnected const> MotorsConnectedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::animatics_smart_motor::MotorsConnected_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::animatics_smart_motor::MotorsConnected_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace animatics_smart_motor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'animatics_smart_motor': ['/home/capra/Ibex/src/animatics_smart_motor/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::animatics_smart_motor::MotorsConnected_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::animatics_smart_motor::MotorsConnected_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::animatics_smart_motor::MotorsConnected_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::animatics_smart_motor::MotorsConnected_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::animatics_smart_motor::MotorsConnected_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::animatics_smart_motor::MotorsConnected_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::animatics_smart_motor::MotorsConnected_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0cdaf65159c7f3563426650fb8d3f64";
  }

  static const char* value(const ::animatics_smart_motor::MotorsConnected_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0cdaf65159c7f35ULL;
  static const uint64_t static_value2 = 0x63426650fb8d3f64ULL;
};

template<class ContainerAllocator>
struct DataType< ::animatics_smart_motor::MotorsConnected_<ContainerAllocator> >
{
  static const char* value()
  {
    return "animatics_smart_motor/MotorsConnected";
  }

  static const char* value(const ::animatics_smart_motor::MotorsConnected_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::animatics_smart_motor::MotorsConnected_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool connected\n\
";
  }

  static const char* value(const ::animatics_smart_motor::MotorsConnected_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::animatics_smart_motor::MotorsConnected_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.connected);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MotorsConnected_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::animatics_smart_motor::MotorsConnected_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::animatics_smart_motor::MotorsConnected_<ContainerAllocator>& v)
  {
    s << indent << "connected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.connected);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANIMATICS_SMART_MOTOR_MESSAGE_MOTORSCONNECTED_H
