// Generated by gencpp from file capra_gps/AddLatlongGoalRequest.msg
// DO NOT EDIT!


#ifndef CAPRA_GPS_MESSAGE_ADDLATLONGGOALREQUEST_H
#define CAPRA_GPS_MESSAGE_ADDLATLONGGOALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/NavSatFix.h>

namespace capra_gps
{
template <class ContainerAllocator>
struct AddLatlongGoalRequest_
{
  typedef AddLatlongGoalRequest_<ContainerAllocator> Type;

  AddLatlongGoalRequest_()
    : goal_latlong()  {
    }
  AddLatlongGoalRequest_(const ContainerAllocator& _alloc)
    : goal_latlong(_alloc)  {
    }



   typedef  ::sensor_msgs::NavSatFix_<ContainerAllocator>  _goal_latlong_type;
  _goal_latlong_type goal_latlong;




  typedef boost::shared_ptr< ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddLatlongGoalRequest_

typedef ::capra_gps::AddLatlongGoalRequest_<std::allocator<void> > AddLatlongGoalRequest;

typedef boost::shared_ptr< ::capra_gps::AddLatlongGoalRequest > AddLatlongGoalRequestPtr;
typedef boost::shared_ptr< ::capra_gps::AddLatlongGoalRequest const> AddLatlongGoalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace capra_gps

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d67e83511d8fcf8b3f5e847c14bf473a";
  }

  static const char* value(const ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd67e83511d8fcf8bULL;
  static const uint64_t static_value2 = 0x3f5e847c14bf473aULL;
};

template<class ContainerAllocator>
struct DataType< ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "capra_gps/AddLatlongGoalRequest";
  }

  static const char* value(const ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/NavSatFix goal_latlong\n\
\n\
================================================================================\n\
MSG: sensor_msgs/NavSatFix\n\
# Navigation Satellite fix for any Global Navigation Satellite System\n\
#\n\
# Specified using the WGS 84 reference ellipsoid\n\
\n\
# header.stamp specifies the ROS time for this measurement (the\n\
#        corresponding satellite time may be reported using the\n\
#        sensor_msgs/TimeReference message).\n\
#\n\
# header.frame_id is the frame of reference reported by the satellite\n\
#        receiver, usually the location of the antenna.  This is a\n\
#        Euclidean frame relative to the vehicle, not a reference\n\
#        ellipsoid.\n\
Header header\n\
\n\
# satellite fix status information\n\
NavSatStatus status\n\
\n\
# Latitude [degrees]. Positive is north of equator; negative is south.\n\
float64 latitude\n\
\n\
# Longitude [degrees]. Positive is east of prime meridian; negative is west.\n\
float64 longitude\n\
\n\
# Altitude [m]. Positive is above the WGS 84 ellipsoid\n\
# (quiet NaN if no altitude is available).\n\
float64 altitude\n\
\n\
# Position covariance [m^2] defined relative to a tangential plane\n\
# through the reported position. The components are East, North, and\n\
# Up (ENU), in row-major order.\n\
#\n\
# Beware: this coordinate system exhibits singularities at the poles.\n\
\n\
float64[9] position_covariance\n\
\n\
# If the covariance of the fix is known, fill it in completely. If the\n\
# GPS receiver provides the variance of each measurement, put them\n\
# along the diagonal. If only Dilution of Precision is available,\n\
# estimate an approximate covariance from that.\n\
\n\
uint8 COVARIANCE_TYPE_UNKNOWN = 0\n\
uint8 COVARIANCE_TYPE_APPROXIMATED = 1\n\
uint8 COVARIANCE_TYPE_DIAGONAL_KNOWN = 2\n\
uint8 COVARIANCE_TYPE_KNOWN = 3\n\
\n\
uint8 position_covariance_type\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/NavSatStatus\n\
# Navigation Satellite fix status for any Global Navigation Satellite System\n\
\n\
# Whether to output an augmented fix is determined by both the fix\n\
# type and the last time differential corrections were received.  A\n\
# fix is valid when status >= STATUS_FIX.\n\
\n\
int8 STATUS_NO_FIX =  -1        # unable to fix position\n\
int8 STATUS_FIX =      0        # unaugmented fix\n\
int8 STATUS_SBAS_FIX = 1        # with satellite-based augmentation\n\
int8 STATUS_GBAS_FIX = 2        # with ground-based augmentation\n\
\n\
int8 status\n\
\n\
# Bits defining which Global Navigation Satellite System signals were\n\
# used by the receiver.\n\
\n\
uint16 SERVICE_GPS =     1\n\
uint16 SERVICE_GLONASS = 2\n\
uint16 SERVICE_COMPASS = 4      # includes BeiDou.\n\
uint16 SERVICE_GALILEO = 8\n\
\n\
uint16 service\n\
";
  }

  static const char* value(const ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_latlong);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AddLatlongGoalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::capra_gps::AddLatlongGoalRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal_latlong: ";
    s << std::endl;
    Printer< ::sensor_msgs::NavSatFix_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_latlong);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAPRA_GPS_MESSAGE_ADDLATLONGGOALREQUEST_H
