// Generated by gencpp from file capra_gps/AddLatlongGoalResponse.msg
// DO NOT EDIT!


#ifndef CAPRA_GPS_MESSAGE_ADDLATLONGGOALRESPONSE_H
#define CAPRA_GPS_MESSAGE_ADDLATLONGGOALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace capra_gps
{
template <class ContainerAllocator>
struct AddLatlongGoalResponse_
{
  typedef AddLatlongGoalResponse_<ContainerAllocator> Type;

  AddLatlongGoalResponse_()
    : goal_xy()  {
    }
  AddLatlongGoalResponse_(const ContainerAllocator& _alloc)
    : goal_xy(_alloc)  {
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _goal_xy_type;
  _goal_xy_type goal_xy;




  typedef boost::shared_ptr< ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddLatlongGoalResponse_

typedef ::capra_gps::AddLatlongGoalResponse_<std::allocator<void> > AddLatlongGoalResponse;

typedef boost::shared_ptr< ::capra_gps::AddLatlongGoalResponse > AddLatlongGoalResponsePtr;
typedef boost::shared_ptr< ::capra_gps::AddLatlongGoalResponse const> AddLatlongGoalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace capra_gps

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "436d4e120d41d247330b721f1289cc92";
  }

  static const char* value(const ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x436d4e120d41d247ULL;
  static const uint64_t static_value2 = 0x330b721f1289cc92ULL;
};

template<class ContainerAllocator>
struct DataType< ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "capra_gps/AddLatlongGoalResponse";
  }

  static const char* value(const ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped goal_xy\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_xy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AddLatlongGoalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::capra_gps::AddLatlongGoalResponse_<ContainerAllocator>& v)
  {
    s << indent << "goal_xy: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_xy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAPRA_GPS_MESSAGE_ADDLATLONGGOALRESPONSE_H
