// Generated by gencpp from file capra_gps/AddLatlongGoal.msg
// DO NOT EDIT!


#ifndef CAPRA_GPS_MESSAGE_ADDLATLONGGOAL_H
#define CAPRA_GPS_MESSAGE_ADDLATLONGGOAL_H

#include <ros/service_traits.h>


#include <capra_gps/AddLatlongGoalRequest.h>
#include <capra_gps/AddLatlongGoalResponse.h>


namespace capra_gps
{

struct AddLatlongGoal
{

typedef AddLatlongGoalRequest Request;
typedef AddLatlongGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddLatlongGoal
} // namespace capra_gps


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::capra_gps::AddLatlongGoal > {
  static const char* value()
  {
    return "8f63823983f4fc627a448ec343bfcaa5";
  }

  static const char* value(const ::capra_gps::AddLatlongGoal&) { return value(); }
};

template<>
struct DataType< ::capra_gps::AddLatlongGoal > {
  static const char* value()
  {
    return "capra_gps/AddLatlongGoal";
  }

  static const char* value(const ::capra_gps::AddLatlongGoal&) { return value(); }
};


// service_traits::MD5Sum< ::capra_gps::AddLatlongGoalRequest> should match 
// service_traits::MD5Sum< ::capra_gps::AddLatlongGoal > 
template<>
struct MD5Sum< ::capra_gps::AddLatlongGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::capra_gps::AddLatlongGoal >::value();
  }
  static const char* value(const ::capra_gps::AddLatlongGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_gps::AddLatlongGoalRequest> should match 
// service_traits::DataType< ::capra_gps::AddLatlongGoal > 
template<>
struct DataType< ::capra_gps::AddLatlongGoalRequest>
{
  static const char* value()
  {
    return DataType< ::capra_gps::AddLatlongGoal >::value();
  }
  static const char* value(const ::capra_gps::AddLatlongGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::capra_gps::AddLatlongGoalResponse> should match 
// service_traits::MD5Sum< ::capra_gps::AddLatlongGoal > 
template<>
struct MD5Sum< ::capra_gps::AddLatlongGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::capra_gps::AddLatlongGoal >::value();
  }
  static const char* value(const ::capra_gps::AddLatlongGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_gps::AddLatlongGoalResponse> should match 
// service_traits::DataType< ::capra_gps::AddLatlongGoal > 
template<>
struct DataType< ::capra_gps::AddLatlongGoalResponse>
{
  static const char* value()
  {
    return DataType< ::capra_gps::AddLatlongGoal >::value();
  }
  static const char* value(const ::capra_gps::AddLatlongGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAPRA_GPS_MESSAGE_ADDLATLONGGOAL_H
