// Generated by gencpp from file capra_controlpanel/Set.msg
// DO NOT EDIT!


#ifndef CAPRA_CONTROLPANEL_MESSAGE_SET_H
#define CAPRA_CONTROLPANEL_MESSAGE_SET_H

#include <ros/service_traits.h>


#include <capra_controlpanel/SetRequest.h>
#include <capra_controlpanel/SetResponse.h>


namespace capra_controlpanel
{

struct Set
{

typedef SetRequest Request;
typedef SetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Set
} // namespace capra_controlpanel


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::capra_controlpanel::Set > {
  static const char* value()
  {
    return "76acd565e38625a7cf6a67bfb94c503f";
  }

  static const char* value(const ::capra_controlpanel::Set&) { return value(); }
};

template<>
struct DataType< ::capra_controlpanel::Set > {
  static const char* value()
  {
    return "capra_controlpanel/Set";
  }

  static const char* value(const ::capra_controlpanel::Set&) { return value(); }
};


// service_traits::MD5Sum< ::capra_controlpanel::SetRequest> should match 
// service_traits::MD5Sum< ::capra_controlpanel::Set > 
template<>
struct MD5Sum< ::capra_controlpanel::SetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::capra_controlpanel::Set >::value();
  }
  static const char* value(const ::capra_controlpanel::SetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_controlpanel::SetRequest> should match 
// service_traits::DataType< ::capra_controlpanel::Set > 
template<>
struct DataType< ::capra_controlpanel::SetRequest>
{
  static const char* value()
  {
    return DataType< ::capra_controlpanel::Set >::value();
  }
  static const char* value(const ::capra_controlpanel::SetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::capra_controlpanel::SetResponse> should match 
// service_traits::MD5Sum< ::capra_controlpanel::Set > 
template<>
struct MD5Sum< ::capra_controlpanel::SetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::capra_controlpanel::Set >::value();
  }
  static const char* value(const ::capra_controlpanel::SetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_controlpanel::SetResponse> should match 
// service_traits::DataType< ::capra_controlpanel::Set > 
template<>
struct DataType< ::capra_controlpanel::SetResponse>
{
  static const char* value()
  {
    return DataType< ::capra_controlpanel::Set >::value();
  }
  static const char* value(const ::capra_controlpanel::SetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAPRA_CONTROLPANEL_MESSAGE_SET_H
