// Generated by gencpp from file capra_controlpanel/SetResponse.msg
// DO NOT EDIT!


#ifndef CAPRA_CONTROLPANEL_MESSAGE_SETRESPONSE_H
#define CAPRA_CONTROLPANEL_MESSAGE_SETRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace capra_controlpanel
{
template <class ContainerAllocator>
struct SetResponse_
{
  typedef SetResponse_<ContainerAllocator> Type;

  SetResponse_()
    : success(false)  {
    }
  SetResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
    }



   typedef uint8_t _success_type;
  _success_type success;




  typedef boost::shared_ptr< ::capra_controlpanel::SetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::capra_controlpanel::SetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetResponse_

typedef ::capra_controlpanel::SetResponse_<std::allocator<void> > SetResponse;

typedef boost::shared_ptr< ::capra_controlpanel::SetResponse > SetResponsePtr;
typedef boost::shared_ptr< ::capra_controlpanel::SetResponse const> SetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::capra_controlpanel::SetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::capra_controlpanel::SetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace capra_controlpanel

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'capra_controlpanel': ['/home/capra/Ibex/src/capra_controlpanel/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::capra_controlpanel::SetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::capra_controlpanel::SetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capra_controlpanel::SetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capra_controlpanel::SetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capra_controlpanel::SetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capra_controlpanel::SetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::capra_controlpanel::SetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::capra_controlpanel::SetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::capra_controlpanel::SetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "capra_controlpanel/SetResponse";
  }

  static const char* value(const ::capra_controlpanel::SetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::capra_controlpanel::SetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
\n\
";
  }

  static const char* value(const ::capra_controlpanel::SetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::capra_controlpanel::SetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::capra_controlpanel::SetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::capra_controlpanel::SetResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAPRA_CONTROLPANEL_MESSAGE_SETRESPONSE_H
