#!/usr/bin/env bash

rosrun camera_calibration cameracalibrator.py -s 5x8 -q 0.1 right:=/right_camera/camera/image_color left:=/left_camera/camera/image_color right_camera:=/right_camera/camera left_camera:=/left_camera/camera --approximate=0.03
