(cl:defpackage capra_gps-srv
  (:use )
  (:export
   "ROTATE"
   "<ROTATE-REQUEST>"
   "ROTATE-REQUEST"
   "<ROTATE-RESPONSE>"
   "ROTATE-RESPONSE"
   "ADDLATLONGGOAL"
   "<ADDLATLONGGOAL-REQUEST>"
   "ADDLATLONGGOAL-REQUEST"
   "<ADDLATLONGGOAL-RESPONSE>"
   "ADDLATLONGGOAL-RESPONSE"
  ))

