// Generated by gencpp from file juvav_recovery/RunResponse.msg
// DO NOT EDIT!


#ifndef JUVAV_RECOVERY_MESSAGE_RUNRESPONSE_H
#define JUVAV_RECOVERY_MESSAGE_RUNRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace juvav_recovery
{
template <class ContainerAllocator>
struct RunResponse_
{
  typedef RunResponse_<ContainerAllocator> Type;

  RunResponse_()
    : success(false)  {
    }
  RunResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
    }



   typedef uint8_t _success_type;
  _success_type success;




  typedef boost::shared_ptr< ::juvav_recovery::RunResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::juvav_recovery::RunResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RunResponse_

typedef ::juvav_recovery::RunResponse_<std::allocator<void> > RunResponse;

typedef boost::shared_ptr< ::juvav_recovery::RunResponse > RunResponsePtr;
typedef boost::shared_ptr< ::juvav_recovery::RunResponse const> RunResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::juvav_recovery::RunResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::juvav_recovery::RunResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace juvav_recovery

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::juvav_recovery::RunResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::juvav_recovery::RunResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::juvav_recovery::RunResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::juvav_recovery::RunResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::juvav_recovery::RunResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::juvav_recovery::RunResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::juvav_recovery::RunResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::juvav_recovery::RunResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::juvav_recovery::RunResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "juvav_recovery/RunResponse";
  }

  static const char* value(const ::juvav_recovery::RunResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::juvav_recovery::RunResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
";
  }

  static const char* value(const ::juvav_recovery::RunResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::juvav_recovery::RunResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RunResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::juvav_recovery::RunResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::juvav_recovery::RunResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JUVAV_RECOVERY_MESSAGE_RUNRESPONSE_H
