set(_CATKIN_CURRENT_PACKAGE "capra_msgs")
set(capra_msgs_MAINTAINER "mathieu <mathieu@todo.todo>")
set(capra_msgs_DEPRECATED "")
set(capra_msgs_VERSION "0.0.0")
set(capra_msgs_BUILD_DEPENDS "message_generation" "std_msgs" "geometry_msgs")
set(capra_msgs_RUN_DEPENDS "message_runtime" "std_msgs" "geometry_msgs")
set(capra_msgs_BUILDTOOL_DEPENDS "catkin")