(cl:in-package roboteq_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MOTOR_CURRENT-VAL
          MOTOR_CURRENT
          MOTOR_POWER-VAL
          MOTOR_POWER
          COMMANDED_VELOCITY-VAL
          COMMANDED_VELOCITY
          MEASURED_VELOCITY-VAL
          MEASURED_VELOCITY
          MEASURED_POSITION-VAL
          MEASURED_POSITION
          SUPPLY_VOLTAGE-VAL
          SUPPLY_VOLTAGE
          SUPPLY_CURRENT-VAL
          SUPPLY_CURRENT
          MOTOR_TEMPERATURE-VAL
          MOTOR_TEMPERATURE
          CHANNEL_TEMPERATURE-VAL
          CHANNEL_TEMPERATURE
))