// Generated by gencpp from file capra_motor_calibrator/CalibrateMotor.msg
// DO NOT EDIT!


#ifndef CAPRA_MOTOR_CALIBRATOR_MESSAGE_CALIBRATEMOTOR_H
#define CAPRA_MOTOR_CALIBRATOR_MESSAGE_CALIBRATEMOTOR_H

#include <ros/service_traits.h>


#include <capra_motor_calibrator/CalibrateMotorRequest.h>
#include <capra_motor_calibrator/CalibrateMotorResponse.h>


namespace capra_motor_calibrator
{

struct CalibrateMotor
{

typedef CalibrateMotorRequest Request;
typedef CalibrateMotorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalibrateMotor
} // namespace capra_motor_calibrator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::capra_motor_calibrator::CalibrateMotor > {
  static const char* value()
  {
    return "cfd7f0162e5ce4a552a1a2922ba01fc1";
  }

  static const char* value(const ::capra_motor_calibrator::CalibrateMotor&) { return value(); }
};

template<>
struct DataType< ::capra_motor_calibrator::CalibrateMotor > {
  static const char* value()
  {
    return "capra_motor_calibrator/CalibrateMotor";
  }

  static const char* value(const ::capra_motor_calibrator::CalibrateMotor&) { return value(); }
};


// service_traits::MD5Sum< ::capra_motor_calibrator::CalibrateMotorRequest> should match 
// service_traits::MD5Sum< ::capra_motor_calibrator::CalibrateMotor > 
template<>
struct MD5Sum< ::capra_motor_calibrator::CalibrateMotorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::capra_motor_calibrator::CalibrateMotor >::value();
  }
  static const char* value(const ::capra_motor_calibrator::CalibrateMotorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_motor_calibrator::CalibrateMotorRequest> should match 
// service_traits::DataType< ::capra_motor_calibrator::CalibrateMotor > 
template<>
struct DataType< ::capra_motor_calibrator::CalibrateMotorRequest>
{
  static const char* value()
  {
    return DataType< ::capra_motor_calibrator::CalibrateMotor >::value();
  }
  static const char* value(const ::capra_motor_calibrator::CalibrateMotorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::capra_motor_calibrator::CalibrateMotorResponse> should match 
// service_traits::MD5Sum< ::capra_motor_calibrator::CalibrateMotor > 
template<>
struct MD5Sum< ::capra_motor_calibrator::CalibrateMotorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::capra_motor_calibrator::CalibrateMotor >::value();
  }
  static const char* value(const ::capra_motor_calibrator::CalibrateMotorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::capra_motor_calibrator::CalibrateMotorResponse> should match 
// service_traits::DataType< ::capra_motor_calibrator::CalibrateMotor > 
template<>
struct DataType< ::capra_motor_calibrator::CalibrateMotorResponse>
{
  static const char* value()
  {
    return DataType< ::capra_motor_calibrator::CalibrateMotor >::value();
  }
  static const char* value(const ::capra_motor_calibrator::CalibrateMotorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAPRA_MOTOR_CALIBRATOR_MESSAGE_CALIBRATEMOTOR_H
