set(_CATKIN_CURRENT_PACKAGE "capra_gps")
set(capra_gps_MAINTAINER "Gabriel Kenderessy <g@brie.lk>")
set(capra_gps_DEPRECATED "")
set(capra_gps_VERSION "0.0.0")
set(capra_gps_BUILD_DEPENDS "rospy" "std_msgs" "nav_msgs" "sensor_msgs")
set(capra_gps_RUN_DEPENDS "rospy" "std_msgs" "nav_msgs" "sensor_msgs")
set(capra_gps_BUILDTOOL_DEPENDS "catkin")