(cl:defpackage move_base_msgs-msg
  (:use )
  (:export
   "<MOVEBASEACTIONFEEDBACK>"
   "MOVEBASEACTIONFEEDBACK"
   "<MOVEBASERESULT>"
   "MOVEBASERESULT"
   "<MOVEBASEACTIONGOAL>"
   "MOVEBASEACTIONGOAL"
   "<MOVEBASEFEEDBACK>"
   "MOVEBASEFEEDBACK"
   "<MOVEBASEACTION>"
   "MOVEBASEACTION"
   "<MOVEBASEACTIONRESULT>"
   "MOVEBASEACTIONRESULT"
   "<MOVEBASEGOAL>"
   "MOVEBASEGOAL"
  ))

