set(_CATKIN_CURRENT_PACKAGE "roboteq_msgs")
set(roboteq_msgs_MAINTAINER "Mike Purvis <mpurvis@clearpathrobotics.com>")
set(roboteq_msgs_DEPRECATED "")
set(roboteq_msgs_VERSION "0.2.0")
set(roboteq_msgs_BUILD_DEPENDS "message_generation" "std_msgs")
set(roboteq_msgs_RUN_DEPENDS "message_runtime" "std_msgs")
set(roboteq_msgs_BUILDTOOL_DEPENDS "catkin")